services:
  # app:
  #   build: .
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - NODE_ENV=production
  #     - MONGO_URI=mongodb://mongo:27017/coffeeRater
  #   depends_on:
  #     - mongo

  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: aA123456
      MONGO_INITDB_DATABASE: coffee
